version: "3.2"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    container_name: jenkins

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  
  


  nexus:
    container_name: nexus
    hostname: nexus
    image: sonatype/nexus3:latest  # Use latest Nexus image
    ports:
      - 8081:8081  # Map container port 8081 to host port 8081 (Nexus UI)
    volumes:
      - nexus_data:/var/sonatype-work/nexus3  # Persistent storage for Nexus data
    environment:
      - SONATYPE_NE=nexus  # Set initial admin password (change for production)
    # restart: unless-stopped

#networks:
#   jenkins:
#     external: true
#     driver: bridge

  # sonarqube:
  #   external: true
  #   driver: bridge
  
  # nexus:
  #   external: true
  #   driver: bridge


volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  nexus_data:







    
